{
  pkgs,
  config,
  lib,
  myvars,
  mylib,
  ...
}:
with lib;
let
  cfgWayland = config.modules.desktop.wayland;
in
{
  imports = mylib.scanPaths ./. ++ [ ../base ];

  options.modules.desktop = {
    wayland = {
      enable = mkEnableOption "Wayland Display Server";
    };
  };

  # 只有一个元素，mkMerge 没有任何作用，目的是未来可能会在列表里添加其他元素
  config = mkMerge [
    (mkIf cfgWayland.enable {
      ####################################################################
      #  NixOS's Configuration for Wayland based Window Manager
      ####################################################################
      services = {
        # 解决可能的熵池问题，如果系统在生成加密随机数（用于处理密码哈希）时由于“熵”不足，会导致几秒钟的阻塞
        haveged.enable = true;
        xserver.enable = false; # disable xorg server
        # https://wiki.archlinux.org/title/Greetd
        greetd = {
          enable = true;
          settings = {
            default_session = {
              user = myvars.username;
              # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
              # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
              # command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
              command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
            };
          };
        };
      };

      # fix https://github.com/ryan4yin/nix-config/issues/10
      # security.pam.services.swaylock = { };
    })
  ];
}
