# Input configuration ──────────────────────────────────────────────────────────
# [input]
# xkb_layout = us,fr
# xkb_variant = dvorak,bepo

# Output configuration ─────────────────────────────────────────────────────────
[output:eDP-1]
mode = 1920x1080@60000
position = 0,0
transform = normal
scale = 1.000000

# You can get the names of your outputs with wlr-randr.
# See also kanshi for configuring your outputs automatically.
# https://wayland.emersion.fr/kanshi/
# See Output options for a complete reference.
# https://github.com/WayfireWM/wayfire/wiki/Configuration#output

# Core options ─────────────────────────────────────────────────────────────────
[core]
plugins = \
  alpha \
  animate \
  autostart \
  command \
  cube \
  decoration \
  expo \
  fast-switcher \
  fisheye \
  grid \
  idle \
  invert \
  move \
  oswitch \
  place \
  resize \
  switcher \
  vswitch \
  window-rules \
  wm-actions \
  wobbly \
  wrot \
  zoom

# Note: [blur] is not enabled by default, because it can be resource-intensive.

# Close focused window.
close_top_view = <super> KEY_C

# Workspaces arranged into a grid: 3 × 3.
vwidth = 3
vheight = 3

# Prefer client-side decoration or server-side decoration
preferred_decoration_mode = client

# Mouse bindings ───────────────────────────────────────────────────────────────
# Drag windows by holding down Super and left mouse button.
[move]
activate = <super> BTN_LEFT

# Resize them with right mouse button + Super.
[resize]
activate = <super> BTN_RIGHT

[zoom]
modifier = <super>

# Change opacity by scrolling with Super + Alt.
[alpha]
modifier = <super> <alt> KEY_O

# Rotate windows with the mouse.
[wrot]
activate = <super> <ctrl> BTN_RIGHT

[fisheye]
toggle = <super> <ctrl> KEY_F

# Startup commands ─────────────────────────────────────────────────────────────
[autostart]
autostart_wf_shell = true

proxy = cfw

# background = mpvpaper -o "no-audio loop" eDP-1 ~/Videos/mp4/heidong.mp4
background = swww init; swww img ~/wall/pics/top/11.jpg &

bar = waybar

inputmethod = fcitx5

outputs = kanshi

notifications = dunst

gamma = wlsunset -l 90.0:0.0 -t 4000 &

idle = swayidle before-sleep swaylock

portal = /usr/lib/xdg-desktop-portal

# [idle]
# toggle = <super> KEY_Z
# screensaver_timeout = 600
# dpms_timeout = 900

# Applications ─────────────────────────────────────────────────────────────────
[command]
binding_terminal = <alt> <shift> KEY_ENTER
command_terminal = alacritty

binding_launcher = <super> KEY_O
command_launcher = rofi -show drun

binding_logout = <alt> <shift> KEY_Q
command_logout = wlogout

binding_lock = <super> KEY_L
command_lock = swaylock

# Screenshots
binding_screenshot_interactive = <super> KEY_P
command_screenshot_interactive = grim -g "$(slurp)" - | wl-copy; notify-send "Over! Over!"
binding_screenshot = <super> <shift> KEY_P
command_screenshot = grim $(date '+%F_%T').webp; notify-send "已截图到 Clipboard!"

# Volume controls
repeatable_binding_volume_up = KEY_VOLUMEUP
command_volume_up = pamixer -i 5
repeatable_binding_volume_down = KEY_VOLUMEDOWN
command_volume_down = pamixer -d 5
binding_mute = KEY_MUTE
command_mute = pamixer -t

# Screen brightness
repeatable_binding_light_up = KEY_BRIGHTNESSUP
command_light_up = brightness set +10%
repeatable_binding_light_down = KEY_BRIGHTNESSDOWN
command_light_down = brightness set 10%-

# self use
binding_terminal = <super> KEY_T
command_terminal = notify-send -u low `date +"%H:%M:%S"`

# Windows ──────────────────────────────────────────────────────────────────────
[switcher]
next_view = <alt> KEY_TAB
prev_view = <alt> <shift> KEY_TAB
[fast-switcher]
activate = <super> KEY_S

# Workspaces ───────────────────────────────────────────────────────────────────
[vswitch]
binding_left = <ctrl> KEY_LEFT
binding_down = <ctrl> KEY_DOWN
binding_up = <ctrl> KEY_UP
binding_right = <ctrl> KEY_RIGHT
with_win_left = <ctrl> <alt> KEY_LEFT
with_win_down = <ctrl> <alt> KEY_DOWN
with_win_up = <ctrl> <alt> KEY_UP
with_win_right = <ctrl> <alt> KEY_RIGHT
binding_1 = <super> KEY_1
binding_2 = <super> KEY_2
binding_3 = <super> KEY_3
binding_4 = <super> KEY_4
binding_5 = <super> KEY_5
binding_6 = <super> KEY_6
binding_7 = <super> KEY_7
binding_8 = <super> KEY_8
binding_9 = <super> KEY_9

[expo]
toggle = <super>

select_workspace_1 = KEY_1
select_workspace_2 = KEY_2
select_workspace_3 = KEY_3
select_workspace_4 = KEY_4
select_workspace_5 = KEY_5
select_workspace_6 = KEY_6
select_workspace_7 = KEY_7
select_workspace_8 = KEY_8
select_workspace_9 = KEY_9

# Outputs ──────────────────────────────────────────────────────────────────────
# Invert the colors of the whole output.
[invert]
toggle = <super> <ctrl> <shift> KEY_C

# Rules ────────────────────────────────────────────────────────────────────────
[window-rules]
alacritty_rule1 = on created if app_id is "Alacritty" then maximize
# alacritty_rule2 = on created if app_id is "Alacritty" then set alpha 0.8
# clash_rule = on created if app_id is "clash" then minimized

[resize]
activate = <super>

[wm-actions]
minimize = <super> KEY_M
toggle_fullscreen = <super> KEY_0
